---
- name: create vm
  hosts: centos
  #vars_files:
   # - ./group_vars/windows.yml
  
  tasks:


    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: Datacenter1
        validate_certs: no
        folder: /Datacenter1/vm
        name: alexvm
        state: poweredon
        esxi_hostname: "{{ esxi_hostname }}"
        guest_id: centos64Guest
        disk:
          - size_gb: 10
            type: thin
            datastore: datastore1
        hardware:
          memory_mb: 512
          num_cpus: 1
          scsi: paravirtual
